### ISSUE TITLE
Can parse multiple times, even when parse was successful

### ISSUE THREAD

**Issue by ryannitz** [ZekyTeky/Team6#34]
Steps: 
-Click parse transcripts button.
-Click however many times more. 

Expected result: Every parse will create a new set of data.
Actual Result: Every parse will double the data in the system, giving improper results. 

Potential actions:
-We could lock the parse button until a certain condition is met.
-We could find a way to clear all data from the system every time we click the parse button.

**Comment by uwera** [comment]
- Added a parse counter to keep track of how many times the Parse button has been clicked.
ParseTranscripts button throws an IllegalArgumentException when the parse button is clicked multiple times.
A message is also shown in the GUI to alert the user that a particular set of transcripts has already been parsed.
