### ISSUE TITLE
Output results are not the right file format. 

### ISSUE THREAD

**Issue by ryannitz** [ZekyTeky/Team6#36]
Steps to reproduce:
-Run application.
-Click 'Parse transcripts' button
-Click 'Write to Excel' button

Expected result: The output will be compatible to be opened with the latest Microsoft excel application (xlsx).

Actual Result: The output has the wrong file extension (xsl). The output must be right clicked and 'opened-with' to work with excel, and has many error messages upon opening. 

Solutions: Moving the HSSF components to XSSF should mitigate this issue.

**Comment by uwera** [comment]
HSSF components now changed to XSSF. Excel outputs are now written to  "Results.xslx" instead of "Results.xsl"
