### ISSUE TITLE
Add global distribution to the excel file.

### ISSUE THREAD

**Issue by ryannitz** [ZekyTeky/Team6#42]
Implement global distribution in a new excel sheet. All system functions are in place but they need to be hooked into excel

**Comment by ryannitz** [comment]
Implemented. please review and close if there are no comments or concerns

**Comment by uwera** [comment]
Looks good. My only concern is the name of the sheet. Can we change it to "Global Distribution" instead of distributions since we have so many other distributions?

**Comment by uwera** [comment]
- The excel sheet containing global and year distributions is now named "Global Distributions" to differentiate it from the Raw & Area Distributions.
