### ISSUE TITLE
Implement the rankConfig within the system

### ISSUE THREAD

**Issue by ryannitz** [ZekyTeky/Team6#57]
The Cohort.addTranscript() currently uses hardcoded values to determine the rank of each transcript. We must provide a way for the system to read a user-defined rank configuration for assigning the rank. 

Note: The current values must be used as the default if no configuration is provided.

**Comment by uwera** [comment]
- Created a rank schema class to read in the margins for second year, third year and fourth year min credit hours. 
- removed hard coded values previously in Cohort.addTranscript() and replaced them with get methods that return the minimum credit hours defined in the rankConfig file.
